### ISSUE TITLE
不确定文章

### ISSUE THREAD

**Issue by yi-Xu-0100** [J-F-Liu/toolbox#2]
我看了这个 https://j-f-liu.gitbooks.io/toolbox/content/Tool/Web.html ，其中有一篇链接文章，[99%的人都理解错了HTTP中GET与POST的区别](https://zhuanlan.zhihu.com/p/22536382)，我点了原文看了一遍，巧的很，我知乎推荐阅读中居然又有一个这个文章，[听说『99% 的人都理解错了 HTTP 中 GET 与 POST 的区别』？？](https://zhuanlan.zhihu.com/p/25028045)，然后小白的我不知道谁是真的了……一脸懵逼，不知如何理解？

**Comment by J-F-Liu** [comment]
看了一下，后一篇的说法也是对的，两篇结合起来认识就更完整了。
